
// This file was auto-generated by ML.NET Model Builder. 

using Recomendation;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Userid = 123546F,
    Mobid = 1F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


Console.WriteLine($"Userid: {123546F}");
Console.WriteLine($"Mobid: {1F}");
Console.WriteLine($"Rating: {74.32433F}");


Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

