
// This file was auto-generated by ML.NET Model Builder. 

using RatingMobs;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Userid = 12345F,
    Performance = 5F,
    Display = 8F,
    Camera = 6F,
    Battary = 8F,
    BuildQuality = 8F,
    Price = 265F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


Console.WriteLine($"Userid: {12345F}");
Console.WriteLine($"Performance: {5F}");
Console.WriteLine($"Display: {8F}");
Console.WriteLine($"Camera: {6F}");
Console.WriteLine($"Battary: {8F}");
Console.WriteLine($"BuildQuality: {8F}");
Console.WriteLine($"Rating: {65F}");
Console.WriteLine($"Price: {265F}");


Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

